name: deploy-site
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Build Nix derivation
        run: |
          nix build .#default
          echo "site output is in result/"

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result

  deploy:
    needs: build-website

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
